var idCrvs = charIDToTypeID( "Crvs" );
    var desc152 = new ActionDescriptor();
    var idpresetKind = stringIDToTypeID( "presetKind" );
    var idpresetKindType = stringIDToTypeID( "presetKindType" );
    var idpresetKindCustom = stringIDToTypeID( "presetKindCustom" );
    desc152.putEnumerated( idpresetKind, idpresetKindType, idpresetKindCustom );
    var idAdjs = charIDToTypeID( "Adjs" );
        var list1 = new ActionList();
            var desc153 = new ActionDescriptor();
            var idChnl = charIDToTypeID( "Chnl" );
                var ref3 = new ActionReference();
                var idChnl = charIDToTypeID( "Chnl" );
                var idChnl = charIDToTypeID( "Chnl" );
                var idCmps = charIDToTypeID( "Cmps" );
                ref3.putEnumerated( idChnl, idChnl, idCmps );
            desc153.putReference( idChnl, ref3 );
            var idCrv = charIDToTypeID( "Crv " );
                var list2 = new ActionList();
                    var desc154 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc154.putDouble( idHrzn, 179.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc154.putDouble( idVrtc, 0.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list2.putObject( idPnt, desc154 );
                    var desc155 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc155.putDouble( idHrzn, 255.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc155.putDouble( idVrtc, 255.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list2.putObject( idPnt, desc155 );
            desc153.putList( idCrv, list2 );
        var idCrvA = charIDToTypeID( "CrvA" );
        list1.putObject( idCrvA, desc153 );
    desc152.putList( idAdjs, list1 );
executeAction( idCrvs, desc152, DialogModes.NO );